COMMON_FLAGS="-O2 -pipe -march=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

MAKEOPTS="-j8 -l12"
EMERGE_DEFAULT_OPTS="--jobs=8 --load-average=8 --autounmask-write"

USE="X -systemd -bluetooth -kde -gnome -nvidia -intel"
ACCEPT_KEYWORDS="~amd64"

VIDEO_CARDS="amdgpu radeonsi"
INPUT_DEVICES="libinput"

ACCEPT_LICENSE="*"
GRUB_PLATFORMS="efi-64"

DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
