# Window size
initial_window_width 120c
initial_window_height 28c

# Font
font_family JetBrains Mono
font_size 22.0

# Disable tab bar
tab_bar_style hidden

# Window padding
window_padding_width 0

# Performance
repaint_delay 6
sync_to_monitor yes

# Transparency
background_opacity 0.0

# Theme
include current-theme.conf
# Or use a Catppuccin Mocha theme file if installed:
# include themes/Catppuccin-Mocha.conf

# Keybindings
map ctrl+shift+r change_font_size all 0

#cursor trail
cursor_trail 1
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.05
cursor_blink true

